flip_and_rgb2gray:
	mpicc flip_and_rgb2gray_serial.c -o flip_and_rgb2gray_serial
	mpicc flip_and_rgb2gray_parallel.c -o flip_and_rgb2gray_parallel
clean:
	rm flip_and_rgb2gray_parallel flip_and_rgb2gray_serial 
