#!/bin/sh
#mpirun -np 1 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Lena.512.ppm"
#mpirun -np 1 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Lena.512.ppm"

#mpirun -np 9 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/CatLogo.128.ppm"
#mpirun -np 9 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Clown.256.ppm"
#mpirun -np 9 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Embryos.512.ppm"
#mpirun -np 9 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Iggy.1024.ppm"

#mpirun -np 1 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/CatLogo.128.ppm"
#mpirun -np 1 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Clown.256.ppm"
#mpirun -np 1 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Embryos.512.ppm"
#mpirun -np 1 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Iggy.1024.ppm"

#mpirun -np 1 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Iggy.1024.ppm"
#mpirun -np 3 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Lena.512.ppm"
#mpirun -np 4 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Lena.512.ppm"
#mpirun -np 5 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Lena.512.ppm"
#mpirun -np 6 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Lena.512.ppm"
#mpirun -np 7 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Lena.512.ppm"
#mpirun -np 8 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Lena.512.ppm"
#mpirun -np 5 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Iggy.1024.ppm"
#mpirun -np 10 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Iggy.1024.ppm"
#mpirun -np 15 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Iggy.1024.ppm"
#mpirun -np 20 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Iggy.1024.ppm"
mpirun -np 25 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Iggy.1024.ppm"
#mpirun -np 1 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Iggy.1024.ppm"
#mpirun -np 9 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/Iggy.1024.ppm"
#mpirun -np 1 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/cake.ppm"
#mpirun -np 9 -hostfile hosts ./flip_and_rgb2gray_parallel "ppm/cake.ppm"
