/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "dp2_20111599_p1.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
get_time_1(void *argp, int *clnt_res, CLIENT *clnt)
{
    clnt_control(clnt, CLSET_RETRY_TIMEOUT, &TIMEOUT);
	return (clnt_call(clnt, GET_TIME,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delay_1(int *argp, int *clnt_res, CLIENT *clnt)
{
    clnt_control(clnt, CLSET_RETRY_TIMEOUT, &TIMEOUT);
	return (clnt_call(clnt, DELAY,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
