/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dp2_20111599_p1.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

// headers.
#include <pthread.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
// globlas.
int tod = 0;
pthread_rwlock_t rwlock;
struct serv_thread_arg
{
    struct svc_req *rqstp;
    SVCXPRT *transp;
};
pthread_t serv_thread_tid;
pthread_attr_t serv_thread_attr;
// increment tod thread.
void* tod_thread(void *arg)
{
    while (1)
    {
        sleep(1);
        pthread_rwlock_wrlock(&rwlock);
        ++tod;
        pthread_rwlock_unlock(&rwlock);
    }
    // NOT REACHED.
    pthread_exit(0);
}
// serv clients' requests.
void* serv_thread(void *arg)
{
    union {
        int delay_1_arg;
    } argument;
    union {
        int get_time_1_res;
        int delay_1_res;
    } result;
    bool_t retval;
    xdrproc_t _xdr_argument, _xdr_result;
    bool_t (*local)(char *, void *, struct svc_req *);

    struct serv_thread_arg *args = (struct serv_thread_arg *)arg;
    struct svc_req *rqstp = args->rqstp;
    register SVCXPRT *transp = args->transp;

    switch (rqstp->rq_proc) {
    case NULLPROC:
        printf("NULL\n");
        (void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
        return;

    case GET_TIME:
        printf("GET\n");
        _xdr_argument = (xdrproc_t) xdr_void;
        _xdr_result = (xdrproc_t) xdr_int;
        local = (bool_t (*) (char *, void *,  struct svc_req *))get_time_1_svc;
        break;

    case DELAY:
        printf("DELAY\n");
        _xdr_argument = (xdrproc_t) xdr_int;
        _xdr_result = (xdrproc_t) xdr_int;
        local = (bool_t (*) (char *, void *,  struct svc_req *))delay_1_svc;
        break;

    default:
        svcerr_noproc (transp);
        return;
    }
    memset ((char *)&argument, 0, sizeof (argument));
    if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
        svcerr_decode (transp);
        return;
    }
    retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
    if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
        svcerr_systemerr (transp);
    }
    if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
        fprintf (stderr, "%s", "unable to free arguments");
        exit (1);
    }
    if (!dp2_20111599_p1_rpc_1_freeresult (transp, _xdr_result, (caddr_t) &result))
        fprintf (stderr, "%s", "unable to free results");

    return;
}

static void
dp2_20111599_p1_rpc_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
    struct serv_thread_arg *arg = (struct serv_thread_arg *)calloc(1, sizeof(struct serv_thread_arg));
    arg->rqstp = rqstp;
    arg->transp = transp;
    
    printf("serv_thread created !\n");

    pthread_attr_setdetachstate(&serv_thread_attr, PTHREAD_CREATE_DETACHED);
    pthread_create(&serv_thread_tid, &serv_thread_attr, serv_thread, (void *)arg);
}

int
main (int argc, char **argv)
{
    register SVCXPRT *transp;
    pthread_t tid;
    pthread_attr_t attr;
    
    pmap_unset (DP2_20111599_P1_RPC, DP2_20111599_P1_RPC_VER);

    transp = svcudp_create(RPC_ANYSOCK);
    if (transp == NULL) {
        fprintf (stderr, "%s", "cannot create udp service.");
        exit(1);
    }
    if (!svc_register(transp, DP2_20111599_P1_RPC, DP2_20111599_P1_RPC_VER, dp2_20111599_p1_rpc_1, IPPROTO_UDP)) {
        fprintf (stderr, "%s", "unable to register (DP2_20111599_P1_RPC, DP2_20111599_P1_RPC_VER, udp).");
        exit(1);
    }

    transp = svctcp_create(RPC_ANYSOCK, 0, 0);
    if (transp == NULL) {
        fprintf (stderr, "%s", "cannot create tcp service.");
        exit(1);
    }
    if (!svc_register(transp, DP2_20111599_P1_RPC, DP2_20111599_P1_RPC_VER, dp2_20111599_p1_rpc_1, IPPROTO_TCP)) {
        fprintf (stderr, "%s", "unable to register (DP2_20111599_P1_RPC, DP2_20111599_P1_RPC_VER, tcp).");
        exit(1);
    }
    pthread_attr_init(&attr);
    pthread_rwlock_init(&rwlock, NULL);
    pthread_create(&tid, &attr, tod_thread, NULL);
    svc_run ();
    fprintf (stderr, "%s", "svc_run returned");
    pthread_join(tid, NULL);
    pthread_rwlock_destroy(&rwlock);
    exit (1);
    /* NOTREACHED */
}
