/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */


#include "dp2_20111599_p1.h"

#include <stdio.h>
// rpc call.
void* rpc_call(char *host, int dly)
{
    CLIENT *clnt;

    int r_dly;
    int s_tod, e_tod;

    char *get_time_1_arg;
    int delay_1_arg = dly;

    enum clnt_stat retval_1, retval_2, retval_3;

#ifndef DEBUG
    clnt = clnt_create (host, DP2_20111599_P1_RPC, DP2_20111599_P1_RPC_VER, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        exit (1);
    }
#endif  /* DEBUG */

    retval_1 = get_time_1((void*)&get_time_1_arg, &s_tod, clnt);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
    }
    
    retval_2 = delay_1(&delay_1_arg, &r_dly, clnt);
    if (retval_2 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
    }
    
    retval_3 = get_time_1((void*)&get_time_1_arg, &e_tod, clnt);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
    }
    
    printf("actual / given : %d / %d\n", e_tod - s_tod, dly);
#ifndef DEBUG
    clnt_destroy (clnt);
#endif   /* DEBUG */
}
void
dp2_20111599_p1_rpc_1(char *host)
{
    CLIENT *clnt;
    enum clnt_stat retval_1;
    int result_1;
    char *get_time_1_arg;
    enum clnt_stat retval_2;
    int result_2;
    int  delay_1_arg;

#ifndef DEBUG
    clnt = clnt_create (host, DP2_20111599_P1_RPC, DP2_20111599_P1_RPC_VER, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        exit (1);
    }
#endif  /* DEBUG */

    retval_1 = get_time_1((void*)&get_time_1_arg, &result_1, clnt);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
    }
    retval_2 = delay_1(&delay_1_arg, &result_2, clnt);
    if (retval_2 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
    }
#ifndef DEBUG
    clnt_destroy (clnt);
#endif   /* DEBUG */
}

int
main (int argc, char *argv[])
{
    char *host;
    int dly;
    host = argv[1];
    dly = atoi(argv[2]);
    rpc_call(host, dly);
    
    exit (0);
}
